version: "2.1"
services:
  web-service:
    image: dsp-web-service:latest
    container_name: dsp-web-service
    ports:
      - 8080:80
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
